//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.10 at 04:01:38 PM BST 
//


package com.MaidenAirlineProject.TIBCO.generatedSchemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Annual_Fee" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Bonus_Miles" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Monthly_Miles" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Welcome_Bonus" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Client_Type", namespace = "http://www.tibco.com/schemas/MaidenAirways/Schemas/Schema.xsd9")
public class ClientType {

    @XmlAttribute(name = "Annual_Fee")
    protected String annualFee;
    @XmlAttribute(name = "Bonus_Miles")
    protected String bonusMiles;
    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "Monthly_Miles")
    protected String monthlyMiles;
    @XmlAttribute(name = "Name")
    protected String name;
    @XmlAttribute(name = "Welcome_Bonus")
    protected String welcomeBonus;

    public ClientType() {}

    public ClientType(String annualFee, String bonusMiles, String id, String monthlyMiles, String name, String welcomeBonus) {
        this.annualFee = annualFee;
        this.bonusMiles = bonusMiles;
        this.id = id;
        this.monthlyMiles = monthlyMiles;
        this.name = name;
        this.welcomeBonus = welcomeBonus;
    }

    /**
     * Gets the value of the annualFee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnualFee() {
        return annualFee;
    }

    /**
     * Sets the value of the annualFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnualFee(String value) {
        this.annualFee = value;
    }

    /**
     * Gets the value of the bonusMiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBonusMiles() {
        return bonusMiles;
    }

    /**
     * Sets the value of the bonusMiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBonusMiles(String value) {
        this.bonusMiles = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the monthlyMiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonthlyMiles() {
        return monthlyMiles;
    }

    /**
     * Sets the value of the monthlyMiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonthlyMiles(String value) {
        this.monthlyMiles = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the welcomeBonus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWelcomeBonus() {
        return welcomeBonus;
    }

    /**
     * Sets the value of the welcomeBonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWelcomeBonus(String value) {
        this.welcomeBonus = value;
    }

}
