//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.10 at 04:01:38 PM BST 
//


package com.MaidenAirlineProject.TIBCO.generatedSchemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Arrival_Airport" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Arrival_Date" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Departure_Airport" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Departure_Date" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Flight_Number" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Gate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ID_Airplane" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Miles" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Price" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Status" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Flight", namespace = "http://www.tibco.com/schemas/MaidenAirways/Schemas/Schema.xsd3")
public class Flight {

    @XmlAttribute(name = "Arrival_Airport")
    protected String arrivalAirport;
    @XmlAttribute(name = "Arrival_Date")
    protected String arrivalDate;
    @XmlAttribute(name = "Departure_Airport")
    protected String departureAirport;
    @XmlAttribute(name = "Departure_Date")
    protected String departureDate;
    @XmlAttribute(name = "Flight_Number")
    protected String flightNumber;
    @XmlAttribute(name = "Gate")
    protected String gate;
    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "ID_Airplane")
    protected String idAirplane;
    @XmlAttribute(name = "Miles")
    protected String miles;
    @XmlAttribute(name = "Price")
    protected String price;
    @XmlAttribute(name = "Status")
    protected String status;

    public Flight() {}

    public Flight(String arrivalAirport, String arrivalDate, String departureAirport, String departureDate, String flightNumber, String gate, String id, String idAirplane, String miles, String price, String status) {
        this.arrivalAirport = arrivalAirport;
        this.arrivalDate = arrivalDate;
        this.departureAirport = departureAirport;
        this.departureDate = departureDate;
        this.flightNumber = flightNumber;
        this.gate = gate;
        this.id = id;
        this.idAirplane = idAirplane;
        this.miles = miles;
        this.price = price;
        this.status = status;
    }

    /**
     * Gets the value of the arrivalAirport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalAirport() {
        return arrivalAirport;
    }

    /**
     * Sets the value of the arrivalAirport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalAirport(String value) {
        this.arrivalAirport = value;
    }

    /**
     * Gets the value of the arrivalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalDate() {
        return arrivalDate;
    }

    /**
     * Sets the value of the arrivalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalDate(String value) {
        this.arrivalDate = value;
    }

    /**
     * Gets the value of the departureAirport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureAirport() {
        return departureAirport;
    }

    /**
     * Sets the value of the departureAirport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureAirport(String value) {
        this.departureAirport = value;
    }

    /**
     * Gets the value of the departureDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureDate() {
        return departureDate;
    }

    /**
     * Sets the value of the departureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureDate(String value) {
        this.departureDate = value;
    }

    /**
     * Gets the value of the flightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightNumber() {
        return flightNumber;
    }

    /**
     * Sets the value of the flightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightNumber(String value) {
        this.flightNumber = value;
    }

    /**
     * Gets the value of the gate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGate() {
        return gate;
    }

    /**
     * Sets the value of the gate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGate(String value) {
        this.gate = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the idAirplane property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDAirplane() {
        return idAirplane;
    }

    /**
     * Sets the value of the idAirplane property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDAirplane(String value) {
        this.idAirplane = value;
    }

    /**
     * Gets the value of the miles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiles() {
        return miles;
    }

    /**
     * Sets the value of the miles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiles(String value) {
        this.miles = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrice(String value) {
        this.price = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
