//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.10 at 04:01:38 PM BST 
//


package com.MaidenAirlineProject.TIBCO.generatedSchemas;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.MaidenAirlineProject.TIBCO.generatedSchemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.MaidenAirlineProject.TIBCO.generatedSchemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Airplane }
     * 
     */
    public Airplane createAirplane() {
        return new Airplane();
    }

    /**
     * Create an instance of {@link Airplanes }
     * 
     */
    public Airplanes createAirplanes() {
        return new Airplanes();
    }

    /**
     * Create an instance of {@link StatusAirplane }
     * 
     */
    public StatusAirplane createStatusAirplane() {
        return new StatusAirplane();
    }

    /**
     * Create an instance of {@link SuccessAirplane }
     * 
     */
    public SuccessAirplane createSuccessAirplane() {
        return new SuccessAirplane();
    }

    /**
     * Create an instance of {@link Airport }
     * 
     */
    public Airport createAirport() {
        return new Airport();
    }

    /**
     * Create an instance of {@link Airports }
     * 
     */
    public Airports createAirports() {
        return new Airports();
    }

    /**
     * Create an instance of {@link SearchToken }
     * 
     */
    public SearchToken createSearchToken() {
        return new SearchToken();
    }

    /**
     * Create an instance of {@link Word }
     * 
     */
    public Word createWord() {
        return new Word();
    }

    /**
     * Create an instance of {@link StatusAirport }
     * 
     */
    public StatusAirport createStatusAirport() {
        return new StatusAirport();
    }

    /**
     * Create an instance of {@link SuccessAirport }
     * 
     */
    public SuccessAirport createSuccessAirport() {
        return new SuccessAirport();
    }

    /**
     * Create an instance of {@link Backoffice }
     * 
     */
    public Backoffice createBackoffice() {
        return new Backoffice();
    }

    /**
     * Create an instance of {@link Backoffices }
     * 
     */
    public Backoffices createBackoffices() {
        return new Backoffices();
    }

    /**
     * Create an instance of {@link StatusBackoffice }
     * 
     */
    public StatusBackoffice createStatusBackoffice() {
        return new StatusBackoffice();
    }

    /**
     * Create an instance of {@link SuccessBackoffice }
     * 
     */
    public SuccessBackoffice createSuccessBackoffice() {
        return new SuccessBackoffice();
    }

    /**
     * Create an instance of {@link Booking }
     * 
     */
    public Booking createBooking() {
        return new Booking();
    }

    /**
     * Create an instance of {@link Passengers }
     * 
     */
    public Passengers createPassengers() {
        return new Passengers();
    }

    /**
     * Create an instance of {@link SelectedFlights }
     * 
     */
    public SelectedFlights createSelectedFlights() {
        return new SelectedFlights();
    }

    /**
     * Create an instance of {@link BookingClientFlight }
     * 
     */
    public BookingClientFlight createBookingClientFlight() {
        return new BookingClientFlight();
    }

    /**
     * Create an instance of {@link BookingClientFlights }
     * 
     */
    public BookingClientFlights createBookingClientFlights() {
        return new BookingClientFlights();
    }

    /**
     * Create an instance of {@link Bookings }
     * 
     */
    public Bookings createBookings() {
        return new Bookings();
    }

    /**
     * Create an instance of {@link StatusBooking }
     * 
     */
    public StatusBooking createStatusBooking() {
        return new StatusBooking();
    }

    /**
     * Create an instance of {@link SuccessBooking }
     * 
     */
    public SuccessBooking createSuccessBooking() {
        return new SuccessBooking();
    }

    /**
     * Create an instance of {@link BookingType }
     * 
     */
    public BookingType createBookingType() {
        return new BookingType();
    }

    /**
     * Create an instance of {@link BookingTypes }
     * 
     */
    public BookingTypes createBookingTypes() {
        return new BookingTypes();
    }

    /**
     * Create an instance of {@link StatusBookingType }
     * 
     */
    public StatusBookingType createStatusBookingType() {
        return new StatusBookingType();
    }

    /**
     * Create an instance of {@link SuccessBookingType }
     * 
     */
    public SuccessBookingType createSuccessBookingType() {
        return new SuccessBookingType();
    }

    /**
     * Create an instance of {@link Client }
     * 
     */
    public Client createClient() {
        return new Client();
    }

    /**
     * Create an instance of {@link Clients }
     * 
     */
    public Clients createClients() {
        return new Clients();
    }

    /**
     * Create an instance of {@link StatusClient }
     * 
     */
    public StatusClient createStatusClient() {
        return new StatusClient();
    }

    /**
     * Create an instance of {@link SuccessClient }
     * 
     */
    public SuccessClient createSuccessClient() {
        return new SuccessClient();
    }

    /**
     * Create an instance of {@link ClientType }
     * 
     */
    public ClientType createClientType() {
        return new ClientType();
    }

    /**
     * Create an instance of {@link ClientTypes }
     * 
     */
    public ClientTypes createClientTypes() {
        return new ClientTypes();
    }

    /**
     * Create an instance of {@link StatusClientType }
     * 
     */
    public StatusClientType createStatusClientType() {
        return new StatusClientType();
    }

    /**
     * Create an instance of {@link SuccessClientType }
     * 
     */
    public SuccessClientType createSuccessClientType() {
        return new SuccessClientType();
    }

    /**
     * Create an instance of {@link Flight }
     * 
     */
    public Flight createFlight() {
        return new Flight();
    }

    /**
     * Create an instance of {@link Flights }
     * 
     */
    public Flights createFlights() {
        return new Flights();
    }

    /**
     * Create an instance of {@link StatusFlight }
     * 
     */
    public StatusFlight createStatusFlight() {
        return new StatusFlight();
    }

    /**
     * Create an instance of {@link SuccessFlight }
     * 
     */
    public SuccessFlight createSuccessFlight() {
        return new SuccessFlight();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Roles }
     * 
     */
    public Roles createRoles() {
        return new Roles();
    }

    /**
     * Create an instance of {@link StatusRole }
     * 
     */
    public StatusRole createStatusRole() {
        return new StatusRole();
    }

    /**
     * Create an instance of {@link SuccessRole }
     * 
     */
    public SuccessRole createSuccessRole() {
        return new SuccessRole();
    }

}
