//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.10 at 04:01:38 PM BST 
//


package com.MaidenAirlineProject.TIBCO.generatedSchemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/MaidenAirways/Schemas/Schema.xsd}SuccessAirport"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "successAirport"
})
@XmlRootElement(name = "StatusAirport", namespace = "http://www.tibco.com/schemas/MaidenAirways/Schemas/Schema.xsd")
public class StatusAirport {

    @XmlElement(name = "SuccessAirport", namespace = "http://www.tibco.com/schemas/MaidenAirways/Schemas/Schema.xsd", required = true)
    protected SuccessAirport successAirport;

    /**
     * Gets the value of the successAirport property.
     * 
     * @return
     *     possible object is
     *     {@link SuccessAirport }
     *     
     */
    public SuccessAirport getSuccessAirport() {
        return successAirport;
    }

    /**
     * Sets the value of the successAirport property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuccessAirport }
     *     
     */
    public void setSuccessAirport(SuccessAirport value) {
        this.successAirport = value;
    }

}
